### ISSUE TITLE
JSONDecodeError when using map-gen feature on 1.12.2 map file

### ISSUE THREAD

**Issue by doublehelix457** [zenenwjaimes/nbt-tools#13] opened 2023-03-05 06:26 UTC
Hi there,

First of all great work!

I seem to be having trouble using the --map-gen flag which throws a JsonDecodeError on my map file. Not sure if this is a versioning issue or not.

Either way here is the stack trace:
```
python3 main.py --src-path /home/doublehelix/data --map-gen --output-dir /home/doublehelix/maps
[2023-03-04 23:22:18] INFO:__main__:Generating maps from /home/doublehelix/maps
Generating image for map_9577.dat
Traceback (most recent call last):
  File "main.py", line 344, in <module>
    run()
  File "main.py", line 329, in run
    map_generator(args)
  File "main.py", line 220, in map_generator
    maps.generate_image(
  File "/home/doublehelix/.local/lib/python3.8/site-packages/nbt_tools/mcfiles/main.py", line 27, in generate_image
    colors = map_colors.get_all_colors(map_colors.get_color_data())
  File "/home/doublehelix/.local/lib/python3.8/site-packages/nbt_tools/mcfiles/map_colors.py", line 630, in get_color_data
    return json.loads(color_json)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 531 column 5 (char 7977)
```

Any help would be appreciated!

**Comment by zenenwjaimes** [comment] 2023-03-05 06:32
I don’t have the time at the moment to debug but I can check it out in a few days with a few of my map files. I have a web version of the nbt map rendering if you really want to render your maps now. Check out https://blocky.tools. If you see a garbled version of your map, make sure to enable canvas rendering (mainly Firefox prevents canvas access due to fingerprinting).

**Comment by zenenwjaimes** [comment] 2023-03-05 06:34
You can drop multiple nbt maps into the web app and move them around so they will stitch together in the case of big maps made out of smaller maps. I hope this helps for now. 👍

**Comment by doublehelix457** [comment] 2023-03-05 06:35
Awesome i really appreciate the quick reply. I'm scared to drop a couple thousand map files on the online one :P I dont mind waiting tbh

**Comment by zenenwjaimes** [comment] 2023-03-05 06:37
> Awesome i really appreciate the quick reply. I'm scared to drop a couple thousand map files on the online one :P I dont mind waiting tbh

Ya, it uses your browser to render stuff so definitely don’t do that unless you want to lock it up. I would give a few of them a shot though just to get an idea of what the python app does.

**Comment by zenenwjaimes** [comment] 2023-03-05 06:44
I’ll try and fix it tomorrow (March 5th, latest rhe 6th). I’ll give this high priority since you’re the first one aside from me to use it and I hope it works out for you. 👍

**Comment by doublehelix457** [comment] 2023-03-05 06:55
Omg you wont believe this. It worked when I used the initial commit of map_colors.py. I really really do appreciate the support tho!

**Comment by doublehelix457** [comment] 2023-03-05 06:56
Maybe make a --map-gen-version 1.12.2 feature or something idk

**Comment by zenenwjaimes** [comment] 2023-03-05 06:57
> Omg you wont believe this. It worked when I used the initial commit of map_colors.py. I really really do appreciate the support tho!

I'm checking it out now. The problem is that since I made that commit in v1.16 of minecraft, there were new colors and blocks added since. Give me a bit, working on it now.

**Comment by zenenwjaimes** [comment] 2023-03-05 07:09
Ok, I've fixed the issue and just committed it directly to master. If you do a pull you should get the updated colors for v1.19. Thanks for bringing this one to my attention. Let me know if you have any issues, if not I can close this issue!

**Comment by zenenwjaimes** [comment] 2023-03-05 07:11
And to give you context as to what it was... I had fixed the colors on the web app, but I copy/pasted that fix into the python app. However, I forgot that javascript allows some extra commas at the end of lists so those were causing issues.

**Comment by doublehelix457** [comment] 2023-03-05 07:35
you are fantastic! thanks very much

**Closed as completed** 2023-03-05 07:35 UTC
